package enums;

public enum TypeOfGun {
    BATON,TORCH, HANDCUFFS, SHACKLES, BOMB,
    MASTERKEYSSET, STEELFILE, DRILL, PLIER, WIRECUTTER, CROWBAR, AUTOGEN,
    GUN, PISTOL,
    KNIFE, FINK, DAGGER, FLAIL, KNUCKLE
}